language: cpp
sudo: true
dist: trusty
env:
  global:
  - PATH="$TRAVIS_BUILD_DIR/cmake-download/bin:$PATH"
 
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - doxygen
        - graphviz
    env:
    - DOCUMINTATION=true
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - DOCUMINTATION=false
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
    env:
    - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - DOCUMINTATION=false
  - os: osx
branches:
  except:
    - gh-pages

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        eval "${MATRIX_EVAL}" &&
        mkdir cmake-download && cd cmake-download &&
        curl -O https://cmake.org/files/v3.10/cmake-3.10.0-rc5-Linux-x86_64.sh &&
        bash cmake-3.10.0-rc5-Linux-x86_64.sh --skip-license &&
        cd ..
    else
      brew upgrade cmake || brew install cmake
    fi

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: 
  - |
    if [[ "${DOCUMINTATION}" == true ]]; then
      cd ..
      doxygen doxygen.config
    else
      make
    fi

after_success:
  - |
    if [[ "${DOCUMINTATION}" == true ]]; then
      pwd &&
      zip -r documintation_${TRAVIS_COMMIT}.zip doc/html
    else
      cd .. &&
      pwd &&
      export ARCHIVE_NAME=SyDEVS_${TRAVIS_OS_NAME}_${CXX}_${TRAVIS_COMMIT} &&
      mkdir ${ARCHIVE_NAME} ${ARCHIVE_NAME}\lib ${ARCHIVE_NAME}\include ${ARCHIVE_NAME}\include\sydevs ${ARCHIVE_NAME}\include\sydevs\systems ${ARCHIVE_NAME}\include\sydevs\time ${ARCHIVE_NAME}\include\sydevs\core &&
      cp src\sydevs\core\*.h ${ARCHIVE_NAME}\include\sydevs\core
      cp src\sydevs\systems\*.h ${ARCHIVE_NAME}\include\sydevs\systems
      cp src\sydevs\time\*.h ${ARCHIVE_NAME}\include\sydevs\time
      cp ${TRAVIS_BUILD_DIR}\SyDEVS*.* ${ARCHIVE_NAME}\lib
      cp LICENSE.md ${ARCHIVE_NAME}
      zip -r ${ARCHIVE_NAME}.zip ${ARCHIVE_NAME}
    fi

deploy:
  provider: releases
  api_key: $(GITHUB_OAUTH_TOKEN)
  file_glob: true
  file: *.zip
  skip_cleanup: true
  on:
    tags: true
