language: cpp
sudo: true
dist: trusty
env:
  global:
  - PATH="$TRAVIS_BUILD_DIR/cmake-download/bin:$PATH"
 
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - doxygen
        - graphviz
    env:
    - DOCUMINTATION=true
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - DOCUMINTATION=false
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
    env:
    - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - DOCUMINTATION=false
  - os: osx
branches:
  except:
    - gh-pages

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        eval "${MATRIX_EVAL}" &&
        mkdir cmake-download && cd cmake-download
        curl -O https://cmake.org/files/v3.10/cmake-3.10.0-rc5-Linux-x86_64.sh &&
        bash cmake-3.10.0-rc5-Linux-x86_64.sh --skip-license &&
        cd ..
    else
      brew upgrade cmake || brew install cmake
    fi

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: 
  - |
    if [[ "${DOCUMINTATION}" == true ]]; then
      cd ..
      doxygen doxygen.config
    else
      make
    fi