language: cpp
sudo: true
dist: trusty
env:
  global:
  - PATH="$TRAVIS_BUILD_DIR/cmake-download/bin:$PATH"
 
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
    env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

branches:
  except:
    - gh-pages

before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir cmake-download && cd cmake-download
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        curl -O https://cmake.org/files/v3.10/cmake-3.10.0-rc5-Linux-x86_64.sh &&
        bash cmake-3.10.0-rc5-Linux-x86_64.sh --skip-license
    else
      brew upgrade cmake || brew install cmake
    fi
  - cd ..

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make