version: '1.0.{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MY_VS_VERSION: Visual Studio 14 2015 Win64
      MY_VS_SHORT: vs2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MY_VS_VERSION: Visual Studio 15 2017 Win64
      MY_VS_SHORT: vs2017

branches:
  except:
    - gh-pages
 
platform:
  - x64
 
configuration:
  - Release
  - Debug

before_build:
  - cmake -G "%MY_VS_VERSION%" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\SyDEVS.sln     # path to Visual Studio solution or project
  parallel: true                                   # enable MSBuild parallel builds
  verbosity: normal                                # MSBuild verbosity level {quiet|minimal|normal|detailed}

after_build:
  - cd c:\projects\sydevs
  - if "%APPVEYOR_REPO_TAG%"=="true" (set ARCHIVE_NAME=SyDEVS_Win64_%MY_VS_SHORT%_%CONFIGURATION%_%APPVEYOR_REPO_TAG_NAME%) else (set ARCHIVE_NAME=SyDEVS_Win64_%MY_VS_SHORT%_%CONFIGURATION%_%APPVEYOR_REPO_COMMIT%)
  - mkdir %ARCHIVE_NAME% %ARCHIVE_NAME%\lib %ARCHIVE_NAME%\include %ARCHIVE_NAME%\include\sydevs %ARCHIVE_NAME%\include\sydevs\systems %ARCHIVE_NAME%\include\sydevs\time %ARCHIVE_NAME%\include\sydevs\core
  - copy src\sydevs\core\*.h %ARCHIVE_NAME%\include\sydevs\core
  - copy src\sydevs\systems\*.h %ARCHIVE_NAME%\include\sydevs\systems
  - copy src\sydevs\time\*.h %ARCHIVE_NAME%\include\sydevs\time
  - copy %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\SyDEVS*.* %ARCHIVE_NAME%\lib
  - copy LICENSE.md %ARCHIVE_NAME%
  - copy LICENSE.md %ARCHIVE_NAME%
  - 7z a %ARCHIVE_NAME%.zip %ARCHIVE_NAME%
  - appveyor PushArtifact %ARCHIVE_NAME%.zip

deploy:
  - provider: Environment
    name: SyDEVS-Releases
    artifact: $(ARCHIVE_NAME).zip
    force_update: true
    on:
      appveyor_repo_tag: true
 