version: '1.0.{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MY_VS_VERSION: Visual Studio 14 2015 Win64
      MY_VS_SHORT: vs2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MY_VS_VERSION: Visual Studio 15 2017 Win64
      MY_VS_SHORT: vs2017

branches:
  except:
    - gh-pages
 
platform:
  - x64
 
configuration:
  - Release
  - Debug

before_build:
    - cmake -G "%MY_VS_VERSION%" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\SyDEVS.sln     # path to Visual Studio solution or project
  parallel: true                                   # enable MSBuild parallel builds
  verbosity: normal                                # MSBuild verbosity level {quiet|minimal|normal|detailed}

after_build:
  - set ARCHIVE_NAME=SyDEVS_Win64_%MY_VS_SHORT%_%CONFIGURATION%_%APPVEYOR_REPO_COMMIT%
  - mkdir %APPVEYOR_BUILD_FOLDER%\%ARCHIVE_NAME%
  - copy %APPVEYOR_BUILD_FOLDER%\..\src\sydevs\core\*.h %APPVEYOR_BUILD_FOLDER%\%ARCHIVE_NAME%\include\core
  - copy %APPVEYOR_BUILD_FOLDER%\..\src\sydevs\systems\*.h %APPVEYOR_BUILD_FOLDER%%ARCHIVE_NAME%\include\systems
  - copy %APPVEYOR_BUILD_FOLDER%\..\src\sydevs\time\*.h %APPVEYOR_BUILD_FOLDER%\%ARCHIVE_NAME%\include\time
  - copy %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\SyDEVS*.* %APPVEYOR_BUILD_FOLDER%\%ARCHIVE_NAME%\bin
  - copy %APPVEYOR_BUILD_FOLDER%\..\LICENSE.md %APPVEYOR_BUILD_FOLDER%\%ARCHIVE_NAME%
  - 7z a SyDEVS_Win64_%MY_VS_SHORT%_%CONFIGURATION%_%APPVEYOR_REPO_COMMIT%.zip %APPVEYOR_BUILD_FOLDER%\%ARCHIVE_NAME%

artifacts:
  - path: SyDEVS_Win64_$(MY_VS_SHORT)_$(CONFIGURATION)_$(APPVEYOR_REPO_COMMIT).zip
    name: SyDEVS_Win64_$(MY_VS_SHORT)_$(CONFIGURATION)_$(APPVEYOR_REPO_COMMIT)