version: '1.0.{build}'

image: Visual Studio 2015

branches:
  except:
    - gh-pages
    - ci_cd

platform:
  - x64
 
configuration:
  - Release
  - Debug

before_build:
    - cmake -G "Visual Studio 14 2015 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\SyDEVS.sln
